### ISSUE TITLE
Is the converter still working properly? 

### ISSUE THREAD

**Issue by Istria1704** [YarosMallorca/MissionPlanner-to-Litchi#32]
Hi,

First of all, thanks for the great work. This is exactly what I was looking for.
But I can't seem to get it to work quite right. Could it be that Litchi or MP have changed/updated some stuff on their file formats and the generated csv does not work correctly anymore?

When I follow the "waypoint trigger" mode tutorial, it imports. But there are no "take photo" or "stay" actions in the waypoints. Instead, the waypoint settings are set to "take photo every 1 meter".
Also the speeds and headings are not set.

Altitudes and positions of the way points are fine. 

Any thoughts?

**Comment by YarosMallorca** [comment]
Yes, maybe they changed stuff, I have no idea because I haven't worked on this project for a year now.
Maybe @JoeKae can take a look at it, because currently I'm busy with other projects.

**Comment by JoeKae** [comment]
I'll take a look over the weekend. I'm quite busy at the moment, and my second child is due soon.

**Comment by Istria1704** [comment]
Thanks. And congratulations @JoeKae!

I was looking into the code yesterday evening and I could not find a clear reason. It seems to use a litchi library to set the actions. So maybe that one is outdated? But I must admit I'm not a very proficient coder, only amateur.
I will look into it some more tonight.

**Comment by JoeKae** [comment]
> Thanks. And congratulations @JoeKae!
> 
> I was looking into the code yesterday evening and I could not find a clear reason. It seems to use a litchi library to set the actions. So maybe that one is outdated? But I must admit I'm not a very proficient coder, only amateur. I will look into it some more tonight.

Thank you!
I tested it with the latest version of Mission Planner, and everything works perfectly. Could you provide a sample waypoints file to help me better understand the input for this software?

Additionally, just so you know, I am the maintainer of the library you discovered.

**Comment by JoeKae** [comment]
Stale
